name: snowcube
description: "Stack Over Snow playable prototype."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^9.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cubes/cube_normal.png
    - assets/cubes/cube_crack_1.png
    - assets/cubes/cube_crack_2.png
    - assets/cubes/cube_crack_3.png
    - assets/cubes/cube_crack_4.png
    - assets/cubes/cube_frozen.png
    - assets/ui/

